// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIG2iXlESAoEGx9p3W7aJgS7Cl57JmVTE',
    appId: '1:98968316573:web:012e61af2453377415c274',
    messagingSenderId: '98968316573',
    projectId: 'quizarea-c8594',
    authDomain: 'quizarea-c8594.firebaseapp.com',
    storageBucket: 'quizarea-c8594.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpLvrD3m13UdmlIGj5kIdTChNB_6RjqBE',
    appId: '1:98968316573:android:ec698c743193f71a15c274',
    messagingSenderId: '98968316573',
    projectId: 'quizarea-c8594',
    storageBucket: 'quizarea-c8594.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY6Plk300aygbfDF8I7kfibhv8DT3Usr4',
    appId: '1:98968316573:ios:7ec6f2697df50a9c15c274',
    messagingSenderId: '98968316573',
    projectId: 'quizarea-c8594',
    storageBucket: 'quizarea-c8594.firebasestorage.app',
    iosBundleId: 'com.quizarea.quizarea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY6Plk300aygbfDF8I7kfibhv8DT3Usr4',
    appId: '1:98968316573:ios:7ec6f2697df50a9c15c274',
    messagingSenderId: '98968316573',
    projectId: 'quizarea-c8594',
    storageBucket: 'quizarea-c8594.firebasestorage.app',
    iosBundleId: 'com.quizarea.quizarea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIG2iXlESAoEGx9p3W7aJgS7Cl57JmVTE',
    appId: '1:98968316573:web:a87d2197cc48c0f515c274',
    messagingSenderId: '98968316573',
    projectId: 'quizarea-c8594',
    authDomain: 'quizarea-c8594.firebaseapp.com',
    storageBucket: 'quizarea-c8594.firebasestorage.app',
  );
}
