// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCJbYC5DIwnsyr8x3vw5FB26oMglmon_E',
    appId: '1:846207667478:web:e67b09d67f0e0251d4d437',
    messagingSenderId: '846207667478',
    projectId: 'notetaking-8111c',
    authDomain: 'notetaking-8111c.firebaseapp.com',
    storageBucket: 'notetaking-8111c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEG038XgF3-E9iQqqxEhCNISLhWTpxkGs',
    appId: '1:846207667478:android:5b247bfa3417fdbdd4d437',
    messagingSenderId: '846207667478',
    projectId: 'notetaking-8111c',
    storageBucket: 'notetaking-8111c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlUYuXTuovioujb6Q6ITWd5LXCoCeVlKQ',
    appId: '1:846207667478:ios:c8dfcb5bf0b0c42bd4d437',
    messagingSenderId: '846207667478',
    projectId: 'notetaking-8111c',
    storageBucket: 'notetaking-8111c.firebasestorage.app',
    iosBundleId: 'com.notetaking.notetaking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlUYuXTuovioujb6Q6ITWd5LXCoCeVlKQ',
    appId: '1:846207667478:ios:c8dfcb5bf0b0c42bd4d437',
    messagingSenderId: '846207667478',
    projectId: 'notetaking-8111c',
    storageBucket: 'notetaking-8111c.firebasestorage.app',
    iosBundleId: 'com.notetaking.notetaking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCJbYC5DIwnsyr8x3vw5FB26oMglmon_E',
    appId: '1:846207667478:web:ec69e619992adf3fd4d437',
    messagingSenderId: '846207667478',
    projectId: 'notetaking-8111c',
    authDomain: 'notetaking-8111c.firebaseapp.com',
    storageBucket: 'notetaking-8111c.firebasestorage.app',
  );
}
